### ISSUE TITLE
API commands parameters

### ISSUE THREAD

**Issue by icaroharry** [svk31/steem-rpc#1]
Is there any cheatsheet or something to see which parameters I need to pass for each command? Also, I think it would be nice to have this on the docs.

**Comment by dskvr** [comment]
+1

**Comment by svk31** [comment]
Unfortunately there's no api call that gives you the list of commands with inputs like `help`does in the cli_wallet. I've added links in the README to the API implementation files in the Steem sourcecode, once I have time I might go over them to extract the relevant information.
